services:
  back:
    build:
      context: ../src/
    container_name: back
    ports:
      - "8000:8000"
    env_file:
      - ../src/.env
    depends_on:
      - db
    command: sh ./startup.sh
    volumes:
      - static_volume:/kettik/back_static/
      - media_volume:/kettik/back_media/
      - ../src/:/kettik/

  db:
    image: postgres:14.3-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - back
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/kettik/back_static/
      - media_volume:/kettik/back_media/
  celery:
    build:
      context: ../src/
    container_name: celery
    command: celery -A core worker -l info
    depends_on:
      - back
      - redis
    env_file:
      - ../src/.env
    volumes:
      - ../src/:/kettik/

  celery-beat:
    build:
      context: ../src/
    container_name: celery_beat
    command: celery -A core beat -l info
    depends_on:
      - back
      - redis
    env_file:
      - ../src/.env
    volumes:
      - ../src/:/kettik/

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  postgres_data:
  static_volume:
  media_volume: